version: '3.9'

services:
  backend:
    container_name: fastapi-container
    image: oriontechmen/env-backend
    ports:
      - "8000:8000"
    depends_on:
      - database  

  database:
    container_name: postgres-container
    image: postgres:latest
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=empdb  
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: